version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    container_name: pg_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=prac2
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./prac2.sql:/docker-entrypoint-initdb.d/init.sql
  swing:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - db
volumes:
  db_data: