package org.example.forms;

import org.example.App;
import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ChooseForm {
    private JComboBox<String> comboBox1;
    public JPanel panel1;
    private JButton button1;

    public ChooseForm() {
        GetConverterTypes();
        button1.setText("Перейти");
        button1.addActionListener(e -> {
            switch (comboBox1.getSelectedIndex()) {
                case 0:
                    OpenMr231();
                    break;
                case 1:
                    OpenMr231_3();
                    break;
            }
        });
    }

    private void GetConverterTypes() {
        try {
            Statement statement = App.db.getConnection().createStatement();
            ResultSet res = statement.executeQuery("select type_name from tb_msgtypes");
            while (res.next()) {
                comboBox1.addItem(res.getString(1));
            }
            res.close();
            statement.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void OpenMr231() {
        Mr231Form form = new Mr231Form();
        form.pack();
        form.setVisible(true);
    }

    private void OpenMr231_3() {
        Mr231_3Form form = new Mr231_3Form();
        form.pack();
        form.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setPreferredSize(new Dimension(500, 300));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.CENTER);
        comboBox1 = new JComboBox();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel2.add(comboBox1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
